import ThemeWrapper from "@/components/ThemeWrapper";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="min-h-full w-full" suppressHydrationWarning>
      <body className="bg-globalBg min-h-screen w-full overflow-y-auto">
        <ThemeWrapper enableSystem={true} attribute="class">
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
